--customer data----

select * from [dbo].[Capstone_ Customer_Data_Project]

--retrieve the total number of customerS from each region--

select REGION, count(CUSTOMERID) AS TOTALCUSTOMERS
FROM [dbo].[Capstone_ Customer_Data_Project]
GROUP BY REGION 

--find the most popular SUBSCRIPTION TYPE BY THE NUMBER OF CUSTOMERS--

SELECT TOP 1 SUBSCRIPTIONTYPE, count(CUSTOMERID) AS CUSTOMERS_NO
FROM [dbo].[Capstone_ Customer_Data_Project]
GROUP BY SUBSCRIPTIONTYPE 

--FIND CUSTOMERS WHO CANCEL THEIR SUBSCRIPTION WITHIN 6 MONTHS

SELECT CUSTOMERID, SUBSCRIPTIONSTART,SUBSCRIPTIONEND 
FROM [dbo].[Capstone_ Customer_Data_Project]
WHERE DATEDIFF(MONTH, SUBSCRIPTIONSTART,SUBSCRIPTIONEND) <= 6 AND CANCELED = 1 

--CALCULATE THE AVERAGE SUBSCRIPTION DURATION FOR ALL CUSTOMERS--

SELECT AVG(SUSCRIPTION_DURATION_IN_DAYS) AS AVERAGEDURATION
FROM [dbo].[Capstone_ Customer_Data_Project]

--OR--

SELECT AVG(DATEDIFF(MONTH, SUBSCRIPTIONSTART,SUBSCRIPTIONEND)) AS AVERAGEDURATION
FROM [dbo].[Capstone_ Customer_Data_Project]

--FIND CUSTOMERS WITH SUBSCRIPTION LONGER THAN 12 MONTHS--

SELECT CUSTOMERID FROM [dbo].[Capstone_ Customer_Data_Project]
WHERE SUSCRIPTION_DURATION_IN_DAYS > 365


SELECT CUSTOMERID 
FROM [dbo].[Capstone_ Customer_Data_Project]
WHERE DATEDIFF(MONTH, SUBSCRIPTIONSTART,SUBSCRIPTIONEND) > 12

--CALCULATE TOTAL REVENUE BY SUBSCRIPTION TYPE--

SELECT SUBSCRIPTIONTYPE, SUM(REVENUE) AS TOTAL_REVENUE
FROM [dbo].[Capstone_ Customer_Data_Project]
GROUP BY SUBSCRIPTIONTYPE

--FIND TOP 3 REGIONS BY SUSCRIPTION CANCELLATIONS--

SELECT TOP 3 REGION, COUNT(CANCELED) AS CANCELLATIONS 
FROM [dbo].[Capstone_ Customer_Data_Project]
WHERE CANCELED = 1
GROUP BY REGION
ORDER BY CANCELLATIONS DESC

--FIND THE TOTAL NUMBER OF ACTIVE AND CANCELED SUBSCRIPTIONS--

SELECT SUM(
 CASE
  WHEN CANCELED = 0 THEN 1 ELSE 0 END) AS ACTIVESUBSCRIPTIONS,
  SUM(
  CASE
  WHEN CANCELED = 1 THEN 1 ELSE 0 END) AS CANCELEDSUBSCRIPTIONS 
  FROM [dbo].[Capstone_ Customer_Data_Project]